default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["MAX_THREADS"] || 10 %>
  timeout: 5000
  username: <%= ENV["POSTGRES_USERNAME"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "" %>
  host: <%= ENV["POSTGRES_HOSTNAME"] || "localhost" %>
  port: <%= ENV["POSTGRES_PORT"] || 5432 %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "from_0_to_1_development" %>

test:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "from_0_to_1_test" %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "from_0_to_1_production" %>
